export interface Question {
    id: string;
    text: string;
    difficulty: 'Easy' | 'Medium' | 'Hard';
    xp: number;
}

// Map 'chapter-id' to a list of questions
export const QUESTION_BANK: Record<string, Question[]> = {
    // CBSE Class 10
    'real-numbers': [
        { id: 'qn_rn_1', text: 'Use Euclid\'s division algorithm to find the HCF of 135 and 225.', difficulty: 'Easy', xp: 50 },
        { id: 'qn_rn_2', text: 'Prove that √5 is irrational.', difficulty: 'Hard', xp: 100 }
    ],
    'polynomials': [
        { id: 'qn_poly_1', text: 'Find the zeroes of the quadratic polynomial x² + 7x + 10.', difficulty: 'Medium', xp: 75 }
    ],
    'quadratic-equations': [
        { id: 'qn_quad_1', text: 'Find the roots of the quadratic equation 2x² - 5x + 3 = 0 by factorisation.', difficulty: 'Medium', xp: 80 }
    ],
    'arithmetic-progressions': [
        { id: 'qn_ap_1', text: 'Find the 10th term of the AP: 2, 7, 12, ...', difficulty: 'Easy', xp: 50 }
    ],
    'trigonometry': [
        { id: 'qn_trig_1', text: 'If tan A = 4/3, find the other trigonometric ratios of the angle A.', difficulty: 'Easy', xp: 60 },
        { id: 'qn_trig_2', text: 'Prove that (sin A + cosec A)² + (cos A + sec A)² = 7 + tan² A + cot² A.', difficulty: 'Hard', xp: 120 }
    ],
    // Class 11
    'permutations-and-combinations': [
        { id: 'qn_pnc_1', text: 'How many 3-digit numbers can be formed from the digits 1, 2, 3, 4 and 5 assuming that repetition of the digits is allowed?', difficulty: 'Easy', xp: 50 },
        { id: 'qn_pnc_2', text: 'Find the number of different signals that can be generated by arranging at least 2 flags in order (one below the other) on a vertical staff, if five different flags are available.', difficulty: 'Medium', xp: 100 }
    ],
    // Fallback for missing chapters
    'default': [
        { id: 'qn_default', text: 'Topic questions coming soon. Try asking the AI Tutor to generate a practice problem for this chapter!', difficulty: 'Easy', xp: 10 }
    ]
};

// retrieves a random question for a specific chapter from the static list
// handles normalization of chapter ids to ensure matches
export function getQuestionForChapter(chapterId: string): Question {
    // Normalize key to handle mismatch between syllabus ID and URL slug
    // e.g. "Permutations and Combinations" -> "permutations-and-combinations"
    const normalizedId = chapterId.toLowerCase().replace(/ /g, '-');

    const questions = QUESTION_BANK[normalizedId] || QUESTION_BANK['default'];
    return questions[Math.floor(Math.random() * questions.length)];
}
